@startuml
start
:شروع ETL;
if (زمان‌بندی شده؟) then (بله)
  :اجرای خودکار;
else (خیر)
  :درخواست دستی مدیر;
endif
:استخراج از POS;
:اعتبارسنجی کیفیت;
if (داده معتبر؟) then (بله)
  :تبدیل به مدل کیمبال;
  :بارگذاری در DW;
  :لاگ موفقیت;
else (خیر)
  :لاگ خطا + هشدار;
endif
stop
@enduml